title: "Learning & Projects Hub"
description: "My GitHub Pages site for course notes, programming exercises, and other projects."
author: "GD"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
